<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TraficoTiming.Repository\TraficoTiming.Repository.csproj" />
    <ProjectReference Include="..\TraficoTiming.Database\TraficoTiming.Database.csproj" />
  </ItemGroup>

</Project>
