// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TraficoTiming.Database;

#nullable disable

namespace TraficoTiming.Database.Migrations
{
    [DbContext(typeof(TraficoTimingDbContext))]
    [Migration("20260527182541_InitialTimingCreate")]
    partial class InitialTimingCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TraficoTiming.Database.Entities.ClockSyncRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DriftMs")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<Guid>("FinishDeviceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OffsetMs")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<decimal>("RoundTripDelayMs")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<Guid>("StarterDeviceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SyncQualityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("TimingSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("TimingSessionId");

                    b.ToTable("ClockSyncRecords");
                });

            modelBuilder.Entity("TraficoTiming.Database.Entities.FinishCapture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FinishDeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("FinishLineCalibrationDataJson")
                        .HasColumnType("text");

                    b.Property<decimal>("FrameRate")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)");

                    b.Property<string>("LocalFileId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("RecordingEndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordingStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TimingSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("UploadStatus")
                        .HasColumnType("integer");

                    b.Property<string>("VideoFileUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FinishDeviceId");

                    b.HasIndex("TimingSessionId");

                    b.ToTable("FinishCaptures");
                });

            modelBuilder.Entity("TraficoTiming.Database.Entities.RaceStartEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FlashTriggered")
                        .HasColumnType("boolean");

                    b.Property<bool>("GunSoundPlayed")
                        .HasColumnType("boolean");

                    b.Property<int>("StartMethod")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StarterDeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimingSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StartTimestampUtc");

                    b.HasIndex("TimingSessionId");

                    b.ToTable("RaceStartEvents");
                });

            modelBuilder.Entity("TraficoTiming.Database.Entities.RawTimingResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AdjustedTimeSeconds")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<Guid?>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<string>("BibNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DetectedFinishTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DetectionMethod")
                        .HasColumnType("integer");

                    b.Property<int?>("FrameNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("Lane")
                        .HasColumnType("integer");

                    b.Property<decimal>("RawTimeSeconds")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<string>("ReviewerNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TimingSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("TimingSessionId");

                    b.HasIndex("TimingSessionId", "Lane");

                    b.ToTable("RawTimingResults");
                });

            modelBuilder.Entity("TraficoTiming.Database.Entities.SyncBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TimingSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("TimingSessionId");

                    b.ToTable("SyncBatches");
                });

            modelBuilder.Entity("TraficoTiming.Database.Entities.SyncItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientGeneratedId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SyncBatchId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientGeneratedId")
                        .IsUnique();

                    b.HasIndex("SyncBatchId");

                    b.ToTable("SyncItems");
                });

            modelBuilder.Entity("TraficoTiming.Database.Entities.TimingAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimingSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DeviceId");

                    b.HasIndex("TimingSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("TimingAuditLogs");
                });

            modelBuilder.Entity("TraficoTiming.Database.Entities.TimingDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BatteryLevel")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ClockDriftMs")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<decimal?>("ClockOffsetMs")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<int>("ConnectionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DeviceRole")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TimingSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimingSessionId");

                    b.HasIndex("TimingSessionId", "DeviceRole");

                    b.ToTable("TimingDevices");
                });

            modelBuilder.Entity("TraficoTiming.Database.Entities.TimingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<int>("HeatNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("MeetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Round")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SyncQualityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("MeetId");

                    b.HasIndex("MeetId", "EventId", "HeatNumber");

                    b.ToTable("TimingSessions");
                });

            modelBuilder.Entity("TraficoTiming.Database.Entities.ClockSyncRecord", b =>
                {
                    b.HasOne("TraficoTiming.Database.Entities.TimingSession", "TimingSession")
                        .WithMany("ClockSyncRecords")
                        .HasForeignKey("TimingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimingSession");
                });

            modelBuilder.Entity("TraficoTiming.Database.Entities.FinishCapture", b =>
                {
                    b.HasOne("TraficoTiming.Database.Entities.TimingSession", "TimingSession")
                        .WithMany("FinishCaptures")
                        .HasForeignKey("TimingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimingSession");
                });

            modelBuilder.Entity("TraficoTiming.Database.Entities.RaceStartEvent", b =>
                {
                    b.HasOne("TraficoTiming.Database.Entities.TimingSession", "TimingSession")
                        .WithMany("RaceStartEvents")
                        .HasForeignKey("TimingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimingSession");
                });

            modelBuilder.Entity("TraficoTiming.Database.Entities.RawTimingResult", b =>
                {
                    b.HasOne("TraficoTiming.Database.Entities.TimingSession", "TimingSession")
                        .WithMany("RawTimingResults")
                        .HasForeignKey("TimingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimingSession");
                });

            modelBuilder.Entity("TraficoTiming.Database.Entities.SyncItem", b =>
                {
                    b.HasOne("TraficoTiming.Database.Entities.SyncBatch", "SyncBatch")
                        .WithMany("SyncItems")
                        .HasForeignKey("SyncBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncBatch");
                });

            modelBuilder.Entity("TraficoTiming.Database.Entities.TimingAuditLog", b =>
                {
                    b.HasOne("TraficoTiming.Database.Entities.TimingSession", "TimingSession")
                        .WithMany("AuditLogs")
                        .HasForeignKey("TimingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimingSession");
                });

            modelBuilder.Entity("TraficoTiming.Database.Entities.TimingDevice", b =>
                {
                    b.HasOne("TraficoTiming.Database.Entities.TimingSession", "TimingSession")
                        .WithMany("Devices")
                        .HasForeignKey("TimingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimingSession");
                });

            modelBuilder.Entity("TraficoTiming.Database.Entities.SyncBatch", b =>
                {
                    b.Navigation("SyncItems");
                });

            modelBuilder.Entity("TraficoTiming.Database.Entities.TimingSession", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ClockSyncRecords");

                    b.Navigation("Devices");

                    b.Navigation("FinishCaptures");

                    b.Navigation("RaceStartEvents");

                    b.Navigation("RawTimingResults");
                });
#pragma warning restore 612, 618
        }
    }
}
